FROM php:8.2-apache

# Install Composer
RUN apt-get update && \
    apt-get install -y git && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Enable required Apache modules
RUN a2enmod rewrite

# Change document root to Laravel public directory
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf

# Change ownership of web directory to Apache user
RUN chown -R www-data:www-data /var/www/html

# Change permissions of storage and bootstrap directories
RUN chmod -R 777 /var/www/html
# Restart Apache
RUN service apache2 restart
